// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EstimateSize(arg1:Array<string>,arg2:number):Promise<main.Estimate>;

export function Extract(arg1:string,arg2:string):Promise<main.Result>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetStartupAction():Promise<string>;

export function GetStartupFile():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenArchiveDialog():Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenMultipleFilesDialog():Promise<Array<string>>;

export function OpenNyaFileDialog():Promise<string>;

export function Pack(arg1:main.PackOptions):Promise<main.Result>;

export function Repair(arg1:string):Promise<main.Result>;

export function Test(arg1:string):Promise<main.Result>;

export function Version():Promise<string>;
