// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Extract(arg1) {
  return window['go']['main']['App']['Extract'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetStartupAction() {
  return window['go']['main']['App']['GetStartupAction']();
}

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function Pack(arg1) {
  return window['go']['main']['App']['Pack'](arg1);
}

export function Repair(arg1) {
  return window['go']['main']['App']['Repair'](arg1);
}

export function Test(arg1) {
  return window['go']['main']['App']['Test'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
